apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  containers:
  - name: my-app
    image: yoonjeong/my-app:1.0
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
    ports:
      - containerPort: 8080

--- 
apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    name: nginx
spec:
  # 여기에 Pod에서 사용할 ConfigMap 타입 볼륨 선언
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
    # 여기에 컨테이너에서 사용할 Pod 볼륨 마운트 선언 (/etc/nginx/conf.d로 마운팅)
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
  - name: my-app
    image: yoonjeong/my-app:1.0
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"   