# Service API 버전: v1
# Service 이름: delivery
# Service 네임스페이스: fancy-snackbar
# Service 레이블: service=delivery, project=snackbar
# Service 타입: ClusterIP
# Service 셀렉터: service=delivery, project=snackbar
# Service 포트: 80
# 컨테이너 포트: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  namespace: fancy-snackbar
  labels:
    service: delivery
    project: snackbar
spec:
  replicas: 2
  selector:
    matchLabels:
      service: delivery
      project: snackbar
  template:
    metadata:
      labels:
        service: delivery
        project: snackbar
    spec:
      containers:
      - name: delivery
        image: yoonjeong/my-app:2.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"