# Service API 버전: v1
# Service 이름: home
# Service 네임스페이스: snackbar
# Service 레이블: service=home, project=snackbar
# Service 타입: NodePort
# Service 셀렉터: service=home, project=snackbar
# Service 포트: 80
# 컨테이너 포트: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: home
  namespace: snackbar
  labels:
    service: home
    project: snackbar
spec:
  selector:
    matchLabels:
      service: home
      project: snackbar
  template:
    metadata:
      labels:
        service: home
        project: snackbar
    spec:
      containers:
      - name: home
        image: yoonjeong/home:1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"