# Service API 버전: v1
# Service 이름: order
# Service 네임스페이스: snackbar
# Service 레이블: service=order, project=snackbar
# Service 타입: NodePort
# Service 셀렉터: service=order, project=snackbar
# Service 포트: 80
# 컨테이너 포트: 8080

---

# Service API 버전: v1
# Service 이름: payment
# Service 네임스페이스: snackbar
# Service 레이블: service=payment, project=snackbar
# Service 타입: ClusterIP
# Service 셀렉터: service=payment, project=snackbar
# Service 포트: 80
# 컨테이너 포트: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: snackbar
  labels:
    service: order
    project: snackbar
spec:
  replicas: 2
  selector:
    matchLabels:
      service: order
      project: snackbar
  template:
    metadata:
      labels:
        service: order
        project: snackbar
    spec:
      containers:
      - name: order
        image: yoonjeong/order:1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: snackbar
  labels:
    service: payment
    project: snackbar
spec:
  replicas: 2
  selector:
    matchLabels:
      service: payment
      project: snackbar
  template:
    metadata:
      labels:
        service: payment
        project: snackbar
    spec:
      containers:
      - name: payment
        image: yoonjeong/payment:1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"